apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nw-ingress
spec:
  rules:
    - http:
        paths:
          - path: /configurator
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-panel
                port:
                  number: 80
          - path: /monitoring
            pathType: Prefix
            backend:
              service:
                name: network-monitoring-django
                port:
                  number: 8000          
          - path: /clustering
            pathType: Prefix
            backend:
              service:
                name: clustering
                port:
                  number: 8080