server:
  port: 9001
  servlet:
    context-path: /configurator

generator-service:
  ribbon:
    server-list-refresh-interval: 5

logging:
  level:
    com.netflix.: info
    org.apache.http: info
    ROOT: debug

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: configurator-service

configurator:
  dictionary:
    text: World
